services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cdk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cdk" ]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    image: cp-case-document-knowledge-service
    build:
      context: ..                 # project root
      dockerfile: docker/Dockerfile
    ports:
      - "8083:8082"
    environment:
      CP_CDK_DATASOURCE_URL: jdbc:postgresql://db:5432/cdk
      CP_CDK_DATASOURCE_USERNAME: postgres
      CP_CDK_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8082
      SERVER_SERVLET_CONTEXT_PATH: /casedocumentknowledge-service
      SPRING_APPLICATION_NAME: cp-case-document-knowledge-service

      # Optional: debug
      LOGGING_LEVEL_org.flywaydb: "TRACE"
      MANAGEMENT_TRACING_ENABLED: "false"     # <— Spring relaxed binding for management.tracing.enabled
      TRACING_ENABLED: "false"                # <— matches the placeholder in application.yml
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8082/casedocumentknowledge-service/actuator/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 12
