

import uk.gov.moj.cpp.authz.drools.Outcome;
import uk.gov.moj.cpp.authz.drools.Action;

global uk.gov.moj.cpp.authz.http.providers.UserAndGroupProvider userAndGroupProvider;



rule "Allow POST /casedocumentknowledge-service/queries for LA"
when
  $o: Outcome()
  $a: Action(name == "POST /casedocumentknowledge-service/queries")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers"))
then
  $o.setSuccess(true);
end

rule "Allow GET /query-catalogue for LA users"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.query-catalogue")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers"))
then
  $o.setSuccess(true);
end
