import uk.gov.moj.cpp.authz.drools.Outcome;
import uk.gov.moj.cpp.authz.drools.Action;

global uk.gov.moj.cpp.authz.http.providers.UserAndGroupProvider userAndGroupProvider;

rule "Allow LA – ingestion-process"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.ingestion-process")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge"))
then
  $o.setSuccess(true);
end

rule "Allow LA – queries"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.queries")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","System Users","District Judge"))
then
  $o.setSuccess(true);
end

rule "Allow LA – answers"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.answers")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge"))
then
  $o.setSuccess(true);
end

rule "Allow LA – query-catalogue"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.query-catalogue")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","System Users","District Judge"))
then
  $o.setSuccess(true);
end

rule "Allow LA – document-content"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.document-content")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge"))
then
  $o.setSuccess(true);
end

rule "Allow LA – ingestion sattus"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.ingestion")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge"))
then
  $o.setSuccess(true);
end


rule "Allow LA – ingestion process"
when
  $o: Outcome()
  $a: Action(name == "casedocumentknowledge-service.ingestion-process")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, "Legal Advisers","District Judge"))
then
  $o.setSuccess(true);
end
